In [15]:
 measurements = [
{'city': 'Dubai', 'temperature': 33.},
{'city': 'London', 'temperature': 12.},
{'city': 'San Fransisco', 'temperature': 18.},
]

In [16]:
measurements

[{'city': 'Dubai', 'temperature': 33.0},
 {'city': 'London', 'temperature': 12.0},
 {'city': 'San Fransisco', 'temperature': 18.0}]

In [17]:
from sklearn.feature_extraction import DictVectorizer
vec = DictVectorizer()

In [18]:
vec.fit(measurements)
vec.get_feature_names()

['city=Dubai', 'city=London', 'city=San Fransisco', 'temperature']

In [19]:
vec.transform(measurements).toarray()

array([[  1.,   0.,   0.,  33.],
       [  0.,   1.,   0.,  12.],
       [  0.,   0.,   1.,  18.]])

In [23]:
 measurements2 = [
{'city': 'Seattle', 'temperature': 13.},
{'city': 'New York', 'temperature': 12.},
{'city': 'San Fransisco', 'temperature': 18.},
]
    
vec.fit(measurements2)
vec.get_feature_names()

['city=New York', 'city=San Fransisco', 'city=Seattle', 'temperature']

In [49]:
vec.transform(measurements)

<3x4 sparse matrix of type '<type 'numpy.float64'>'
	with 4 stored elements in Compressed Sparse Row format>

In [25]:
vec.transform(measurements2).toarray()

array([[  0.,   0.,   1.,  13.],
       [  1.,   0.,   0.,  12.],
       [  0.,   1.,   0.,  18.]])

In [26]:
from sklearn.feature_extraction.text import CountVectorizer

In [27]:
vectorizer = CountVectorizer(min_df=1)

In [35]:
corpus = [
'This is the first document.',
'This is the second second document.',
'And the third one.',
'Is this the first document?',
]
vectorizer.fit(corpus)
X = vectorizer.transform(corpus)
X.toarray()    

array([[0, 1, 1, 1, 0, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 2, 1, 0, 1],
       [1, 0, 0, 0, 1, 0, 1, 1, 0],
       [0, 1, 1, 1, 0, 0, 1, 0, 1]])

In [38]:
corpus2 = [
'some other',
'blah blah',
]
corpus3 = [
'my name is some',
'some blah',
    'yeah'
]

In [36]:
vectorizer.fit(corpus2)
X = vectorizer.transform(corpus)
X.toarray()

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [37]:
X = vectorizer.transform(corpus2)
X.toarray()

array([[0, 1, 1],
       [2, 0, 0]])

In [39]:
X = vectorizer.transform(corpus3)
X.toarray()

array([[0, 0, 1],
       [1, 0, 1],
       [0, 0, 0]])

In [29]:
analyze = vectorizer.build_analyzer()
analyze("This is a text document to analyze.")

[u'this', u'is', u'text', u'document', u'to', u'analyze']

In [30]:
vectorizer.get_feature_names()

[u'and',
 u'document',
 u'first',
 u'is',
 u'one',
 u'second',
 u'the',
 u'third',
 u'this']

In [33]:
X.toarray()   

array([[0, 1, 1, 1, 0, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 2, 1, 0, 1],
       [1, 0, 0, 0, 1, 0, 1, 1, 0],
       [0, 1, 1, 1, 0, 0, 1, 0, 1]])

In [34]:
set([1,2,3])

{1, 2, 3}

In [40]:
bigram_vectorizer = CountVectorizer(ngram_range=(1, 2), token_pattern=r'\b\w+\b', min_df=1)
analyze = bigram_vectorizer.build_analyzer()
analyze('Bi-grams are cool!')

[u'bi', u'grams', u'are', u'cool', u'bi grams', u'grams are', u'are cool']

In [41]:
from sklearn.feature_extraction.text import TfidfTransformer
transformer = TfidfTransformer()

In [44]:
transformer.fit_transform(X.toarray()).toarray()

array([[ 0.        ,  0.        ,  1.        ],
       [ 0.79596054,  0.        ,  0.60534851],
       [ 0.        ,  0.        ,  0.        ]])

In [45]:
X.toarray()

array([[0, 0, 1],
       [1, 0, 1],
       [0, 0, 0]])

In [48]:
1 if 1 else 5

1