In [ ]:
import numpy as np
import pandas as pd
from sklearn.cross_validation import StratifiedKFold

loc = '../%s'
#loc = '/home/ec2-user/data/hd/features/%s'

In [1]:
queries = pd.read_pickle(loc % 'FEATURES_WITH_TEXT_1.data')

idx_train = pd.read_pickle(loc % 'LABELS_TRAIN.df')
idx_test = pd.read_pickle(loc % 'LABELS_TEST.df')

In [2]:
queries

query  product_uid  \
id                                                          
1                    90 unitsdegrees bracket       100001   
2                              angle bracket       100001   
3                                  l bracket       100001   
4                           metal l brackets       100001   
5                           simpson sku able       100001   
6                        simpson strong ties       100001   
7                 simpson strong tie hcc 668       100001   
8                            wood connectors       100001   
9                                  deck over       100002   
10                           bath shower kit       100003   
11                            bath drain kit       100003   
12                      one piece tub shower       100003   
13                               solar panel       100004   
16                          rain shower head       100005   
17                        shower only faucet       100005   
14            1 handle shower delta trim kit       100005   
15               delta ashland shower faucet       100005   
18                            convection otr       100006   
19                             cooking stove       100006   
20                      microwave over stove       100006   
21                                microwaves       100006   
22                     microwaves over range       100006   
23                           emergency light       100007   
24                       self tapping screws       100008   
25                        3 1d20 door casing       100009   
26                                 door trim       100009   
27                                   mdf 3d4       100009   
32                                    stakes       100010   
33                    steel landscape edging       100010   
34                               steel stake       100010   
...                                      ...          ...   
240731              bifold oak 6 panel doors       224399   
240732  200 unitsamperes breaker double pole       224400   
240733                     axle locking nuts       224401   
240734                                sheath       224402   
240735                  outdoor patio shades       224403   
240736                          safety signs       224404   
240737                           phone cable       224405   
240738                              vanguard       224406   
240739                          dummy handle       224407   
240740             advanced drainage systems       224408   
240741                               led tvs       224409   
240742                             l molding       224410   
240743                     minwax polycrylic       224411   
240744                             camellias       224412   
240745                      black gas ranges       224413   
240746                      submersible wire       224414   
240747        32 kw generac protector series       224415   
240748                         bathroom taps       224416   
240749            ceiling fan light fixtures       224417   
240750                               peonies       224418   
240751                              paracord       224419   
240752            2 unitsinches 1d4 20 bolts       224420   
240753                           bath chairs       224421   
240754                             1d2 brass       224422   
240755                    pivot shower doors       224423   
240756              24 white storage cabinet       224424   
240757                    adirondack cushion       224425   
240758                                    hb       224426   
240759                           hex sockets       224427   
240760                4 unitsinches hole saw       224428   

                                            product_title  \
id                                                          
1             simpson strong tie strongtie 12 gauge angle   
2           

In [31]:
skf = list(enumerate(StratifiedKFold(idx_train['relevance'], n_folds=5, shuffle=True)))  # [  (i, (train, test)), ... ]

In [32]:
skf

[(0,
  (array([ 1501,  1694,  3824, ..., 74064, 74065, 74066]),
   array([    0,     1,     2, ..., 16814, 16832, 28537]))),
 (1,
  (array([    0,     1,     2, ..., 74064, 74065, 74066]),
   array([ 1501,  1694,  3824, ..., 38337, 53194, 58113]))),
 (2,
  (array([    0,     1,     2, ..., 74064, 74065, 74066]),
   array([23656, 25973, 25975, ..., 57645, 57666, 64678]))),
 (3,
  (array([    0,     1,     2, ..., 74064, 74065, 74066]),
   array([30287, 38249, 38250, ..., 65447, 68559, 68814]))),
 (4,
  (array([    0,     1,     2, ..., 65447, 68559, 68814]),
   array([50199, 50200, 50205, ..., 74064, 74065, 74066])))]

In [56]:
[len(skf[i][1][0]) for i in range(5)]

[59250, 59253, 59254, 59254, 59257]

In [68]:
for (i, (train, test)) in enumerate(StratifiedKFold(idx_train['relevance'], n_folds=5, shuffle=True)):
    idx_train.iloc[train].to_pickle('KFOLD_%d_TRAIN.df' % i)
    idx_train.iloc[test].to_pickle('KFOLD_%d_TEST.df' % i)

In [66]:
data['train_0']['relevance'].mean()

2.3816474261603373

In [65]:
data['test_0']['relevance'].mean()

2.3815792670581089

In [69]:
queries

query  product_uid  \
id                                                          
1                    90 unitsdegrees bracket       100001   
2                              angle bracket       100001   
3                                  l bracket       100001   
4                           metal l brackets       100001   
5                           simpson sku able       100001   
6                        simpson strong ties       100001   
7                 simpson strong tie hcc 668       100001   
8                            wood connectors       100001   
9                                  deck over       100002   
10                           bath shower kit       100003   
11                            bath drain kit       100003   
12                      one piece tub shower       100003   
13                               solar panel       100004   
16                          rain shower head       100005   
17                        shower only faucet       100005   
14            1 handle shower delta trim kit       100005   
15               delta ashland shower faucet       100005   
18                            convection otr       100006   
19                             cooking stove       100006   
20                      microwave over stove       100006   
21                                microwaves       100006   
22                     microwaves over range       100006   
23                           emergency light       100007   
24                       self tapping screws       100008   
25                        3 1d20 door casing       100009   
26                                 door trim       100009   
27                                   mdf 3d4       100009   
32                                    stakes       100010   
33                    steel landscape edging       100010   
34                               steel stake       100010   
...                                      ...          ...   
240731              bifold oak 6 panel doors       224399   
240732  200 unitsamperes breaker double pole       224400   
240733                     axle locking nuts       224401   
240734                                sheath       224402   
240735                  outdoor patio shades       224403   
240736                          safety signs       224404   
240737                           phone cable       224405   
240738                              vanguard       224406   
240739                          dummy handle       224407   
240740             advanced drainage systems       224408   
240741                               led tvs       224409   
240742                             l molding       224410   
240743                     minwax polycrylic       224411   
240744                             camellias       224412   
240745                      black gas ranges       224413   
240746                      submersible wire       224414   
240747        32 kw generac protector series       224415   
240748                         bathroom taps       224416   
240749            ceiling fan light fixtures       224417   
240750                               peonies       224418   
240751                              paracord       224419   
240752            2 unitsinches 1d4 20 bolts       224420   
240753                           bath chairs       224421   
240754                             1d2 brass       224422   
240755                    pivot shower doors       224423   
240756              24 white storage cabinet       224424   
240757                    adirondack cushion       224425   
240758                                    hb       224426   
240759                           hex sockets       224427   
240760                4 unitsinches hole saw       224428   

                                            product_title  \
id                                                          
1             simpson strong tie strongtie 12 gauge angle   
2           